# This is a basic workflow to help you get started with Actions

name: CI for pull-requests

on: pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses: actions/checkout@v2
        
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - run: cd mejournal-ui && ls -alh
      - name: Install dependencies
        run: cd mejournal-ui && yarn install
      - name: build
        run: cd mejournal-ui && ls -alh && yarn test  --watchAll=false --passWithNoTests
